import {mkdir, readFile, writeFile} from "node:fs/promises";
import {dirname, join, relative} from "node:path";
import {fileURLToPath} from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const skillDir = join(root, ".claude-plugin", "react-kit", "skills", "react-kit");

// Docs whose source of truth lives in the library source tree and are copied,
// verbatim, into the shipped skill so installed-plugin users (who have no
// react-kit checkout) can still read them. Edit the `from` file, never the copy.
const copies = [
    {from: "src/form/README.md", to: "form-README.md"},
];

for (const {from, to} of copies) {
    const body = await readFile(join(root, from), "utf8");
    const banner =
        `<!-- GENERATED by scripts/build-skill.mjs from ${from} — do not edit here. ` +
        `Edit ${from} and run \`npm run build:skill\`. -->\n\n`;
    const dest = join(skillDir, to);
    await mkdir(dirname(dest), {recursive: true});
    await writeFile(dest, banner + body);
    console.log(`skill: ${from} -> ${relative(root, dest)}`);
}
